### ISSUE TITLE
Reading OME Metadata fails due to PhysicalSizeZ = 0

### ISSUE THREAD

**Issue by ChrisYanLuc** [AllenCellModeling/czi-to-ome-xslt#19]
## System and Software
* aicsimageio Version: 4.5.2
* Python Version: 3.8.8
* Operating System: Windows10

## Description
Importing the image is all fine but when I try to open the OME metadata it gives the following error:

XMLSchemaValidationError: failed validating 0.0 with XsdMinExclusiveFacet(value=0.0, fixed=False):
Reason: attribute PhysicalSizeZ='0': value has to be greater than 0.0

which states the problem pretty clearly but I do not know how to resolve it and seems to a possible bug. 
The image has a shape of (500, 3, 1, 512, 512) so there is only one z-plane. Therefore it is okay that the PhysicalSizeZ is 0 since the z-values should not matter. And indeed when opening the OME Metadata with another software (Fiji) the PhysicalSizeZ is simply not given and the z-index ("TheZ") is always 0, as expected.
The PhysicalSizeZ should also be accessible in the "normal" metadata and there the Z-Distance is 1um but ScalingZ is 0 (see example below) and X and Y scaling are the same. I have no idea why it is saved like this.

So is this a general problem when importing time series with only one z-plane?

Get the example file [here](https://www.dropbox.com/s/3x9ccfngjkgzoxl/example%20file.zip?dl=0)

## Expected Behavior
Importing the OME Metadata

## Reproduction
```
from aicsimageio import AICSImage
import xml.etree.ElementTree as ET
import xmltodict

file = 'C:/path/to/file.czi'

img = AICSImage(file)

#AICSImage(file).ome_metadata()  #gives error


#To show useful information eventually involved in this problem
print('Shape: ', img.shape)

mdata = img.metadata
mdatadict = xmltodict.parse(ET.tostring(mdata, encoding='utf8').decode('utf8'))['ImageDocument']['Metadata']

for element in mdatadict['Scaling']['Items']['Distance']:
    print(element['@Id'], '-scaling : ', element['Value'])
print('also ScalingX: ', mdatadict['Experiment']['ExperimentBlocks']['AcquisitionBlock']['AcquisitionModeSetup']['ScalingX'])
print('also ScalingY: ', mdatadict['Experiment']['ExperimentBlocks']['AcquisitionBlock']['AcquisitionModeSetup']['ScalingY'])
print('also ScalingZ: ', mdatadict['Experiment']['ExperimentBlocks']['AcquisitionBlock']['AcquisitionModeSetup']['ScalingZ'])
```

**Comment by evamaxfield** [comment]
Hey @ChrisYanLuc! Thanks for the report. I am going to move this issue over to czi-to-ome-xslt as it sounds like this error is likely on the conversion side and not on the specifically aicsimageio side of things.

**Comment by evamaxfield** [comment]
I believe the relevant template is here: https://github.com/AllenCellModeling/czi-to-ome-xslt/blob/f5b86195eced4ecabe72b116d2830344d31e493d/xslt/Pixels.xsl#L70

If I am reading the OME schema correctly: https://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2016-06/ome.html

I think we need to add a check for if the value is 0, we can simply skip adding the OME element because it's optional?

But additionally, it seems we are using a different metadata path from the one you provided in the CZI.

You are using: `/Experiment/ExperimentBlocks/AcquisitionBlock/AcquisitionModeSetup/ScalingX`
We are using:  `/Metadata/Scaling/Items/Distance[@Id=X]/Value`

(or some similar path)

Do you know which is preferred?

**Comment by ChrisYanLuc** [comment]
First thanks moving the issue.

Secound, reading the OME schema, the PhysicalSizeZ is indeed optional and is minExcluvie 0 which should be the reason for the observed error. Your solution of skipping it, if it is 0 seems plausible because I think this is the default value when it is otherwise not used, needed or set. Another way would be to check the other metadata path. But I am wondering why they have different default values if these are really the default values.

Third, since I am rather new with using these files I do not know which matadata path is generally preferred.

**Comment by evamaxfield** [comment]
:shrug: Metadata (especially metadata mapping) is weird

Pinging @joshmoore and @sebi06.

@sebi06, when using aicsimageio, if you call `AICSImage.physical_pixel_sizes` where do you expect those values to come from in the CZI metadata?

@joshmoore, is my above statement about making the Z PhysicalSize optional correct?

**Comment by sebi06** [comment]
From the spec I think one should take the scaling for the "Scaling" node inside the XML / Dict

```md_dict['ImageDocument']['Metadata']['Scaling']```

and not from the Experiment and Acquisition blocks, because those contain the info how the CZI was once acquired etc.

[DS_ZISRAW-FileFormat.pdf](https://github.com/AllenCellModeling/czi-to-ome-xslt/files/8088182/DS_ZISRAW-FileFormat.pdf)


And if I use aicsimageio or aicspylibCZI etc. to get the scaling values I expect them to come from:

```/Metadata/Scaling/Items/Distance[@Id=X]/Value``` etc.

Depending on the acquisition a CZI might have SizeZ = None if the user did not activate the Z-Stack box. This is not the same (i know ...) as activating the z-Stack Acquisition and use excatly one z-plane --> SizeZ = 1 

Does this help?

**Comment by evamaxfield** [comment]
Perfect! Thanks for the info! Sounds like our implementation is correct then.

**Comment by evamaxfield** [comment]
@ChrisYanLuc did you want to try making a PR to resolve this?

**Comment by joshmoore** [comment]
> @joshmoore, is my above statement about making the Z PhysicalSize optional correct?

Sorry for the slow response, yes:

https://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2016-06/ome_xsd.html#Pixels_PhysicalSizeZ

**Comment by ChrisYanLuc** [comment]
@JacksonMaxfield I mean i tried finding the right spot in the code to resolve this but I'm pretty lost since i'm new to this. So im afraid im not gonna make a PR.

**Comment by evamaxfield** [comment]
No worries @ChrisYanLuc, I had some free time this morning so I fixed it real quick. See #20

**Comment by evamaxfield** [comment]
I will merge that, then send a PR to aicsimageio to update. Likely a new aicsimageio release by end of day?

**Comment by evamaxfield** [comment]
Hey @ChrisYanLuc, I just started the release process on `aicsimageio` that should hopefully fix this. v4.6.2 should be out in about 40 minutes. Let me know if the fix didn't work!

**Comment by ChrisYanLuc** [comment]
@JacksonMaxfield 
I am very very very sorry for not noticing this message until now. 
Unfortunatetely another problem occures with both of the newer versions 4.6.2 and 4.6.3.

The error message on both of the newer versions are the same but look more cryptic to me. It seems the Channels ID is the problem there. This time i copied almost the whole error-message from the console in case you can figure out some information from that (see text files). But the probably important part is:

```
XMLSchemaValidationError: failed validating '30693854291175537024503808143238201295-0' with XsdPatternFacets(['(urn:lsid:([\\w\\-\\.]+\\.[\\w\\-\\.]+)+:Channel:\\S+)|(Channel:\\S+...']):

Reason: attribute ID='30693854291175537024503808143238201295-0': value doesn't match any pattern of ['(urn:lsid:([\\w\\-\\.]+\\.[\\w\\-\\.]+)+:Channel:\\S+)|(Channel:\\S+)']

Schema:

  <xsd:pattern xmlns:xsd="http://www.w3.org/2001/XMLSchema" value="(urn:lsid:([\w\-\.]+\.[\w\-\.]+)+:Channel:\S+)|(Channel:\S+)" />

Instance:

  <ome:Channel xmlns:ome="http://www.openmicroscopy.org/Schemas/OME/2016-06" ID="30693854291175537024503808143238201295-0" Name="Ch1" AcquisitionMode="LaserScanningConfocalMicroscopy" IlluminationType="Epifluorescence" ExcitationWavelength="488.00000000000006" ExcitationWavelengthUnit="nm" EmissionWavelength="524.5" EmissionWavelengthUnit="nm" Fluor="EGFP"><ome:DetectorSettings ID="Detector:0:0" Binning="Other" /></ome:Channel>

Path: /ome:OME/ome:Image/ome:Pixels/ome:Channel[1]
```


[error_version_4_5_2.txt](https://github.com/AllenCellModeling/czi-to-ome-xslt/files/8246663/error_version_4_5_2.txt)
[error_version_4_6_2.txt](https://github.com/AllenCellModeling/czi-to-ome-xslt/files/8246665/error_version_4_6_2.txt)

**Comment by evamaxfield** [comment]
This error is basically saying: "Your channel IDs should match the pattern: 'Channel:{integer}'" and currently your channel IDs dont match that pattern. This is likely on us...

Here is the appropriate portion of the converter: https://github.com/AllenCellModeling/czi-to-ome-xslt/blob/main/xslt/Channels.xsl

If you can make a PR to fix it, great, if not, then can you send me the metadata of the original CZI? Just open the file and dump `.metadata` to an xml file please. I will try to get to it at some point in the next week or so.

**Comment by ChrisYanLuc** [comment]
I found a way to work around this error by getting the [free software from ZEISS](https://www.zeiss.de/mikroskopie/produkte/mikroskopsoftware/zen-lite.html?aliId=eyJpIjoiYytuY3I5b2FDYkhzRldaaiIsInQiOiJBVHVrcmtMZXdqdTBlTnJJdjgzclZ3PT0ifQ%253D%253D#zen-lite) (Zen-lite) which allows me to save the files as an .ome.tiff file. Reading these files with aicsimageio is fine and the metadata is what I would expect from ome_metadata from the .czi files:
```
AICSImage(file.czi).ome_metadata #does not work
AICSImage(file.ome.tiff).metadata #works fine
```
I have no idea where the other metadata is which I could access with
`AICSImage(file.czi).metadata` 
and
`AICSImage(file.ome.tiff).ome_metadata`
raises `NotImplementedError`.

Also need to mention that this workaround does not work on version 4.6.2 or .3 but at 4.5.2
on the new versions I get the following message:
```
im = AICSImage('path/to/file.ome.tiff')
Attempted file (path/to/file.ome.tiff) load with reader: aicsimageio.readers.ome_tiff_reader.OmeTiffReader failed with
error: Could not find a schema for XML resource XMLResource(root=<Element '{http://www.openmicroscopy.org/Schemas/OME/2016-06}OME' at 0x0000018615206B80>).
```

**Comment by ChrisYanLuc** [comment]
Here are the metadata files
Metadata using `AICSImage(file.czi).metadata`
[czi_metadata.txt](https://github.com/AllenCellModeling/czi-to-ome-xslt/files/8247839/czi_metadata.txt)

and here the metadata using `AICSImage(file.ome.tiff).metadata`
[ome_metadata.txt](https://github.com/AllenCellModeling/czi-to-ome-xslt/files/8247985/ome_metadata.txt)

**Comment by evamaxfield** [comment]
> I found a way to work around this error by getting the [free software from ZEISS](https://www.zeiss.de/mikroskopie/produkte/mikroskopsoftware/zen-lite.html?aliId=eyJpIjoiYytuY3I5b2FDYkhzRldaaiIsInQiOiJBVHVrcmtMZXdqdTBlTnJJdjgzclZ3PT0ifQ%253D%253D#zen-lite) (Zen-lite) which allows me to save the files as an .ome.tiff file.

> Also need to mention that this workaround does not work on version 4.6.2 or .3 but at 4.5.2
on the new versions I get the following message

That is the point of this library / this work. We noticed that Zeiss was failing to produce correct OME metadata in their "save as OME-TIFF" function. The error you are getting when reading the Zeiss created OME-TIFF fails to validate against the OME metadata specification.

That's what this warning is saying:

> Attempted file (path/to/file.ome.tiff) load with reader: aicsimageio.readers.ome_tiff_reader.OmeTiffReader failed with
error: Could not find a schema for XML resource XMLResource(root=<Element '{http://www.openmicroscopy.org/Schemas/OME/2016-06}OME' at 0x0000018615206B80>).

`aicsimageio` attempted to load the file with our `OmeTiffReader` but the metadata is incorrectly structured / just incorrect / can't be validated.

It's also not an "error", it is simply logging a warning. When you are attempting to read the Zeiss produced OME-TIFF and then trying to use `.ome_metadata` and it fails with `NotImplementedError` it's because the file was read with `TiffReader` not `OmeTiffReader` because, again, the Zeiss produced OME metadata is incorrect and the `OmeTiffReader` will only read files that have valid to the specification OME metadata. And the `TiffReader` literally doesn't have an implementation of the `ome_metadata` function because the attached metadata blob could be anything, not just OME. That is why we have two different readers: one for `OmeTiffReader` and one general `TiffReader`.

> AICSImage(file.ome.tiff).metadata  "works"

Yes it generally is _okay_ to use that. The Zeiss produces metadata is accurate in terms of content, but not in terms of layout / matching the OME specification.

Hope this helps / makes sense.

**Comment by sebi06** [comment]
Hi all,

I just want to point out that PhysicalSizeZ for a CZI can have a None value in case the CZI has no SizeZ dimension.
This is not a bug in the spec but by design.
So I ideally every tool reading the metadata should check for the existence of all those dimensions and then decide on how to deal with non existing dimensions

Because converting a CZI to OME-TIFF is something one should avoid if possible.

**Comment by evamaxfield** [comment]
> Hi all,
> 
> I just want to point out that PhysicalSizeZ for a CZI can have a None value in case the CZI has no SizeZ dimension. This is not a bug in the spec but by design. So I ideally every tool reading the metadata should check for the existence of all those dimensions and then decide on how to deal with non existing dimensions
> 
> Because converting a CZI to OME-TIFF is something one should avoid if possible.

No worries @sebi06, that PhysicalSizeZ thing makes sense and has been solved. Sorry for the additional pings. I will open a new issue to avoid pings.

**Comment by sebi06** [comment]
The issues with the missing XML schema location is currently being fixed. 😊

**Comment by sebi06** [comment]
Pinging me is totally fine. I actually really appreciate it so I know what is going on.
